//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int id { get; set; }
        public string author { get; set; }
        public int id_trading { get; set; }
        public int BBK_id { get; set; }
        public string publication { get; set; }
        public string place { get; set; }
        public Nullable<int> year { get; set; }
        public string name { get; set; }
    
        public virtual bbk bbk { get; set; }
        public virtual trading trading { get; set; }
        public virtual quantity quantity { get; set; }
    }
}
