//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryEntities : DbContext
    {
        public libraryEntities()
            : base("name=libraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bbk> bbk { get; set; }
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<formular> formular { get; set; }
        public virtual DbSet<trading> trading { get; set; }
        public virtual DbSet<quantity> quantity { get; set; }
        public virtual DbSet<roles> roles { get; set; }
    }
}
