//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class quantity
    {
        public int id_book { get; set; }
        public Nullable<int> instook { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual book book { get; set; }
    }
}
